---
- hosts: happy
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: true

  tasks:
  # as there is no internal DNS service, we need to populate theb /etc/hosts
  - name: update /etc/hosts file for name resolution of self
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "127.0.0.1 {{item}}"
      state: present
    with_items: happy
  # as there is no internal DNS service, we need to populate the /etc/hosts
  - name: update /etc/hosts file for name resolution
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{item}}"
      state: present
    when: hostvars[item]['ansible_default_ipv4']['address'] is defined
    with_items: '{{bootstorage}}'

  - name: update repo
    shell:
      cmd: curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -

  - name: install nodejs
    apt:
      pkg: nodejs
      state: present

  - name: create happy directory
    file:
      path: /home/happy
      state: directory

  - name: copy happy js
    copy:
      src: /home/vagrant/happy/index.js
      dest: /home/happy/
      mode: '0755'
      owner: root
      group: root

  - name: copy happy package.json
    copy:
      src: /home/vagrant/happy/package.json
      dest: /home/happy/
      mode: '0755'
      owner: root
      group: root 

  - name: install dependencies
    npm:
      path: /home/happy

  - name: start happy
    command:
      chdir: /home/happy
      cmd: node index.js
    async: 1000
    poll: 0
